//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kütüphane
{
    using System;
    using System.Collections.Generic;
    
    public partial class kullanıcılar
    {
        public int kullanıcı_id { get; set; }
        public string kullanıcı_ad { get; set; }
        public string kullanıcı_soyad { get; set; }
        public string kullanıcı_tc { get; set; }
        public string kullanıcı_mail { get; set; }
        public string kullanıcı_tel { get; set; }
        public Nullable<double> kullanıcı_ceza { get; set; }
    }
}
